---
# Source: wordpress/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wp-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-12.2.5
    app.kubernetes.io/instance: wp
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "MDRiN3piNnM2UQ=="
  mariadb-password: "MnN6eHk0NHRBNQ=="
