---
# Source: wordpress/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wp-wordpress
  namespace: "default"
  labels:
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-16.1.25
    app.kubernetes.io/instance: wp
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  wordpress-password: "S0JNVFNMRDdkQw=="
