resources:
  - 00-persistentvolume.yaml
  - 01-wordpress.yaml

secretGenerator:
- name: mysql-pass
  literals:
  - password=wordpressword

configMapGenerator:
- name: wp-configmap
  literals:
  - WORDPRESS_DB_HOST=wordpress-mysql
  - WORDPRESS_DB_USER=wordpress