resources:
  - 00-persistentvolume.yaml
  - 01-wordpress.yaml

secretGenerator:
- name: mysql-pass
  literals:
  - password=wordpressword

configMapGenerator:
- name: wp-configmap
  literals:
  - wp-db-host=wordpress-mysql
  - wp-db-user=wordpress