resources:
  - 00-persistentvolume.yaml
  - 01-wordpress.yaml
  - 02-mysql.yaml

secretGenerator:
- name: mysql-pass
  literals:
  - password=wordpressword

configMapGenerator:
- name: wp-configmap
  literals:
  - WORDPRESS_DB_HOST=wordpress-mysql
  - WORDPRESS_DB_USER=wordpress
- name: mysql-configmap
  literals:
  - MYSQL_DATABASE=wordpress
  - MYSQL_USER=wordpress